"""whoops, root story to root story id

Revision ID: 9c68b2c1cf99
Revises: 9ffc7374f508
Create Date: 2023-11-15 04:11:01.821250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9c68b2c1cf99'
down_revision: Union[str, None] = '9ffc7374f508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_story_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("name", 'stories', ['root_story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_constraint("name", type_='foreignkey')
        batch_op.drop_column('root_story_id')

    # ### end Alembic commands ###
