"""add pre-gen to scene

Revision ID: f8f67ec54afd
Revises: 1bd659f95bd1
Create Date: 2023-11-17 01:37:30.059599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f8f67ec54afd'
down_revision: Union[str, None] = '1bd659f95bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outline', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("''")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_column('outline')

    # ### end Alembic commands ###
